services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - NODE_ENV=development
    volumes:
      - ./frontend/src:/app/src
      - /app/node_modules

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=db
      - DB_PORT=1234
      - DB_USER=postgres
      - DB_PASSWORD=localhost
      - DB_NAME=recipes
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=localhost
      - POSTGRES_DB=recipes
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
